### ISSUE TITLE
Add picture upload and calendar to edit listing

### ISSUE THREAD

**Issue by aidenszeto** [staynomad/Nomad-Front#238]
Currently we cannot edit pictures and availability in EditListing. For pictures, we can reuse the deletion UI that we currently have for CreateListing, and we should also add an option to upload new photos. Editing the calendar can use the same interface as CreateListing.

**Comment by aidenszeto** [comment]
me and @teekenzie can work on the calendar editing for this

**Comment by teekenzie** [comment]
@aidenszeto ok
