### ISSUE TITLE
Create script to add coordinates to listings

### ISSUE THREAD

**Issue by aidenszeto** [staynomad/Nomad-Front#415]
Because we implemented coordinates after some listings were already created, we need to add coordinates to the older listings that were created before the implementation.

To do this, we should create a script that can detect the listing's address and spit out the coordinate (we should probably use Google Maps API). The resulting coordinates should be in the form:

![image](https://user-images.githubusercontent.com/66970460/111546051-488a3b80-8734-11eb-8c6d-6101caa9d57b.png)

**Comment by nishantbalaji** [comment]
closed on backend
