### ISSUE TITLE
Login Errors with Google

### ISSUE THREAD

**Issue by nishantbalaji** [staynomad/Nomad-Front#462]
Instantly redirects to google login when the "Login" button is clicked and shows this error: 

![image](https://user-images.githubusercontent.com/44332326/121800342-0911a500-cbe6-11eb-9028-b927f7940142.png)

![image](https://user-images.githubusercontent.com/44332326/121800336-04e58780-cbe6-11eb-89b7-be44dc574dad.png)

**Comment by aidenszeto** [comment]
Which account were you signing in with when this happened?

**Comment by nishantbalaji** [comment]
It auto signed in, I'm not sure. Looks like a local issue, probably some conflicts with the Stripe? The `login-bug`  branch works fine.
