### ISSUE TITLE
Stripe payouts button 

### ISSUE THREAD

**Issue by aidenszeto** [staynomad/Nomad-Front#469]
We currently have a standalone tab called "payouts" that consists of only the stripe button. Here's a few options on designing/formatting:
 - Add instructions to "payouts" page to fill up whitespace
 - Move stripe button to "settings" tab or already existing tab
 
 
![image](https://user-images.githubusercontent.com/44332326/122846525-e0ab3a00-d2ba-11eb-9c5f-66c195ed2003.png)

![image](https://user-images.githubusercontent.com/44332326/122846572-f7ea2780-d2ba-11eb-94ca-60e703a16834.png)

**Comment by aidenszeto** [comment]
@nishantbalaji

**Comment by aidenszeto** [comment]
@MikePodo Feel free to drop any suggestions or critiques if you have any

**Comment by MikePodo** [comment]
In terms of UI we could definitely polish this up by having the text/button centered and bigger. Otherwise it seems like it'll work. My only concern is just to make sure that the "Payouts" tab scales well to maintain a smooth mobile responsive experience.

**Comment by nishantbalaji** [comment]
@MikePodo In that case the entire tab would just be one button that depends on if the person is connected to Stripe or not. Why not move that elsewhere?

**Comment by MikePodo** [comment]
@nishantbalaji I was thinking that too. I said it that way because in the attached pictures, it shows a "Payouts" tab like I described.

**Comment by nishantbalaji** [comment]
@MikePodo Yeah, I thought the dashboard would be an integration and made a page but since the dashboard is hosted by Stripe, it'll probably look nicer with some other content on the page.

**Comment by nishantbalaji** [comment]
Lets move the payout button below or next to the edit profile button here: 
![image](https://user-images.githubusercontent.com/44332326/123884340-de229300-d8ff-11eb-9543-0c4430ab6288.png)
