### ISSUE TITLE
Pictures upload button clear/missing

### ISSUE THREAD

**Issue by nishantbalaji** [staynomad/Nomad-Front#499]
# Background

Where do I upload pictures? 
![image](https://user-images.githubusercontent.com/44332326/126838221-eba0289c-ffe6-4490-b6b8-b55fdce88887.png)

# Task

* Create a button to upload images

# Done When

* It is clear to the user where images should be uploaded

**Comment by aidenszeto** [comment]
![image](https://user-images.githubusercontent.com/66970460/127432847-7d4f675c-4d1a-4368-8d06-a677039158fd.png)
Fixed in previous sprint
